/* Copyright (c) 2015 Dennis Bemmann. See the file LICENSE for copying permission. */
/*
Font4x6.js
==============

from FontDennis8_Alt3.png
custom design font desinnée en 4x6 pour ecran 7x7 alfazeta
E.toString() meilleure accélération

Usage:

```
require("Font4x6").add(Graphics);
g.setFont4x6();
g.drawString("\x90 \x91\x92\x93\x94\x95\x96\x97 Dennis8 \x9f \x8c \x8d \x89",0,0);
g.drawString("ça ¿sí? \xbc\xa3 \xbd\xb5\xa6 \x82\x83\x84\x85 \xac\xad\x86",0,12);
g.drawString("\xa0 Bäh böse Ärzte in Küche\xaf",0,24);
```
*/
var font = E.toString(atob("AAAAAPoAwADAAFhw2HDQAGSS/5JMAGCW+DzSDAxSolIMEsAAPEKBAIFCPABIMOAwSAAQEHwQEAABBgAICAgAAgADDDDAAHyKkqJ8AED+AEKGipJiAISSstKMABgoSP4IAOSioqKcADxSkpIMAICAjrDAAGySkpJsAGCSkpR4ACIAASYAEChEACgoKCgoAEQoEABAipBgADxapb1EOH6QkH4A/pKSbAB8goJEAP6CgnwA/pKSggD+kJCAAHyCkt4A/hAQ/gCC/oIABAKC/IAA/hAoxgD+AgICAP5AOED+AP4gEAj+AHyCgnwA/pCQYAB8goqEegD+kJBuAGSSkpJMAMCA/oDAAPwCAv4A+AQCBPgA/AIcAvwAxigQKMYAwCAeIMAAhoqS4gD+goOCAMAwDAMAgIOC/gAgQIBAIAABAQEBAQESfpKCBAAEKioeAH4SEgwAHCIiFAAMEhJ+ABwqKhoACD5IQAAYJSU+AH4QEA4AIL4CAAIBIb4AfggUIgB8AgIAPiAeIB4APiAgHgAcIiIcAD8kJBgAGCQkPwA+ICAQABIqKiQAfBISADwCAj4APAIEOAA8AgwCPAA2CAg2ADgFBT4AJioqMgAQboEA5wCBbhAAQIDAQIAAPFqlpUI8cPh8+HAAcDhwACBg/mAgAAgM/gwIABA4fBAQABAQfDgQAHxERER8AHxE9CRcAHxUbFR8AP58OBAAEDh8/gACAAIAAgB8fHx8fAD+/gD+/gACilIiAgACIlKKAgA+Yu5iPgACAgICAgAGBgYGBgAODg4ODgAeHh4eHgA+Pj4+PgB+fn5+fgD+/v7+/gD+/v7+/gAAAAAA/gD+/gD+/v4A/v7+/gD+/v7+/gA4OHz+/gAMDPBAIACeADhE/kQIABJ8koIEAEQ4KDhEAKhoPmioACh8qqqCAARSqpRAAJCkqKSQAP6CupL+ABKqqqp6ABAoVChEADh8fHw4ADhUbFQ4AP6Cpor+ABAYHBgQAGCQkGAAIiL6IiIASJioSACIqKhQACBAgAB/BAQIfABgkP6A/gAwMAAAAAAASPgIADlFRUU5AEQoVCgQAOgWKl+CAOgQKVONAKj4BgofAAYJUQIAjpQkFA4ADhQklI4ADlSkVA4ATpSUVI4AjjjIOI4ADlS0VA4APkj+kpIAeISFh0gAvqoqIgA+KiqigAA+aqpiAD6qKqIAon4iACJ+ogBivmIAYj5iABB+UkI8AH6QiES+AJyiIhwAHCKinAAMUpJSDABMkpJSjAC8QkJCvAAiFAgUIgA+Q11hPgC8ggI+ADwCgr4AHEKCXgC8AgK8ACAQTpAgAIH/JSQYAH+SkmwABKpqHgAEKmqeAARqql4ABGqqnkCABKoqHoAABGqqfgBMUjxSNAA4RUckAJyqKhgAHCqqmgAcaqpaAByqKpoAon4CACJ+ggBivkIAYj5CAKRKqhoMAF6QkE6AAAySUgwADFKSDAAMUpJMAEySUowAnCIinAAQEFQQEAA6TFRkuAAcgoIeABwCAp6AABxCgl4AHEICHkAAMApKijwAgf8VCAAwigqKPAA="));
var widths = E.toString(atob("BAIEBgYGBgIEBAYGAwQCBQYDBgYGBgYGBgYCAwQGBAUGBQUFBQUFBQUEBgUFBgYFBQYFBgYFBgYGBgUFBQUGBgYFBQUFBQUFBQQFBQQGBQUFBQUFBAUFBgUFBQQCBAYGBgQGBgYGBgYGBQUGBgYGBgYGBgYGBgYGBgQCAwQFBgYGAgYGBgYGBgYGBgYGBgYGBQYFBQQGBgMEBAYGBgYGBQYGBgYGBgYGBQYFBQQEBAQGBgUFBgYGBgYFBQUFBgYFBQUFBgYFBgUFBQUFBAQEBAYGBQUFBQUGBgUGBQYGBQY="));
exports.add = function(graphics) {
  graphics.prototype.setFont4x6 = function() {
    this.setFontCustom(font, 32, widths, 8);
  };
};